% This LilyPond file was generated by Rosegarden 22.12.1
\include "nederlands.ly"
\version "2.24.0"
\header {
    copyright =  \markup { "Copyright "\char ##x00A9" xxxx Copyright Holder" }
    subtitle = "not yet subtitled"
    title = "Not Yet Titled"
    tagline = "Created using Rosegarden 22.12.1 and LilyPond"
}
#(set-global-staff-size 32)
#(set-default-paper-size "a5" 'landscape)
global = { 
    \time 4/4
    \skip 1*6 \skip 2 \skip 4 \skip 64 
}
globalTempo = {
    \tempo 4 = 120  
}
\score {
    << % common
        % Force offset of colliding notes in chords:
        \override Score.NoteColumn.force-hshift = #1.0
        % Allow fingerings inside the staff (configured from export options):
        \override Score.Fingering.staff-padding = #'()

        \context Staff = "track 1" << 
            \set Staff.midiInstrument = "Acoustic Grand Piano"
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo

            \context Voice = "voice 1" {
                % Segment: Acoustic Grand Piano (recorded)
                \override Voice.TextScript.padding = #2.0
                \override MultiMeasureRest.expand-limit = 1
                \once \override Staff.TimeSignature.style = #'numbered 
                \time 4/4
                
                \clef "treble"
                r2 r8 r16 g'' 8.. -\tenuto f'' 16. -\tenuto 
                % warning: overlong bar truncated here |
                \skip 32 r32 r16 e'' 8. -\tenuto d'' -\tenuto f'' 4 -\tenuto e''  |
                d'' 8. -\tenuto c'' 8 r16 c'' 8 -\tenuto d'' -\tenuto e'' -\tenuto r d'' 4 -\tenuto 
                % warning: overlong bar truncated here |
                \skip 2 r16 r32 a' 8 r32 a' 4 -\tenuto 
                % warning: overlong bar truncated here |
%% 5
                \skip 2 r8 b' 4. -\tenuto 
                % warning: overlong bar truncated here |
                \skip 4 \skip 8 r32 
                % warning: overlong bar truncated here |
            } % Voice

            \context Voice = "voice 2" {
                % Segment: Acoustic Grand Piano (recorded)
                \override Voice.TextScript.padding = #2.0
                \override MultiMeasureRest.expand-limit = 1

                \skip 1 
                \clef "treble"
                \key c \major
                r8 < a c' f > 2.. 
                % warning: overlong bar truncated here |
                \skip 2 r8 r4 
                % warning: bar too short, padding with rests
                % 7680 + 3360 < 11520  &&  7/8 < 4/4
                r8  |
                r4 < f' a' d' > 2. -\tenuto 
                % warning: overlong bar truncated here |
%% 5
                \skip 2 \skip 4 r4  |
                r2 r16 < e' g' c' > 4.. -\tenuto 
                % warning: overlong bar truncated here |
                \skip 2 r16 r8 r64 
                % warning: overlong bar truncated here
                % warning: bar too short, padding with rests
                % 23040 + 2651 < 25931  &&  45/64 < 4/4
                r16 r64  |
                \bar "|."
            } % Voice
        >> % Staff (final) ends

    >> % notes

    \layout {
        \context { \Staff \RemoveEmptyStaves }
        \context { \GrandStaff \accepts "Lyrics" }
    }
%     uncomment to enable generating midi file from the lilypond source
%         \midi {
%             \tempo 4 = 120
%         } 
} % score
