#! rake -f

require 'erb'

basename = 'coltrane-random'

def erase_if_exists(filename)
  if File.exist?(filename)
    puts "Erasing #{filename}"
    FileUtils.rm(filename)
  end
end

task :clean do
  erase_if_exists("#{basename}.midi")
  erase_if_exists("#{basename}.pdf")
  erase_if_exists("#{basename}.png")
  erase_if_exists("#{basename}.svg")
end

task :build do
  filename = "#{basename}.ly.erb"
  raw = File.read(filename)
  template = ERB.new(raw)
  result = template.result

  output_filename = "#{basename}.ly"
  File.write(output_filename, result)
  system("lilypond #{output_filename}")
end

task :default => [:build]

